name: Sync Repo from HaroldXL to Hgnv11

on:
  schedule:
    - cron: '0 3 * * *'  # Chạy mỗi ngày lúc 3h sáng UTC (10h sáng VN)
  workflow_dispatch:     # Cho phép chạy thủ công từ GitHub UI

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo (your fork)
        uses: actions/checkout@v3
        with:
          repository: Hgnv11/Smoking-Cessation-Support-Platform
          token: ${{ secrets.PERSONAL_TOKEN }}
          path: target-repo

      - name: Add upstream (original repo)
        run: |
          cd target-repo
          git remote add upstream https://github.com/HaroldXL/Smoking-Cessation-Support-Platform.git
          git fetch upstream
          git merge upstream/main --allow-unrelated-histories -m "Auto-merge from upstream"
          git push origin main
