const CommunityPosts = [
  {
    post_id: 1,
    user_id: 101,
    title: "How I Quit Smoking After 15 Years",
    content: "The first thing I did was write down why I wanted to quit. Every morning, I read that list and reminded myself. When cravings hit, I drank water, went for a walk, or called someone close. The first 3 months were tough, but now I sleep better, breathe easier, and save a lot of money.",
    image: '../src/components/images/community-post-img-1.png',
    post_type: "STORIES",
    is_approved: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    post_id: 2,
    user_id: 102,
    title: "5 Simple Tricks to Beat Cigarette Cravings",
    content: "1. Drink cold water\n2. Chew sugar-free gum\n3. Take 10 deep breaths\n4. Go for a walk\n5. Call someone for support",
    image: '../src/components/images/community-post-img-2.png',
    post_type: "TIPS",
    is_approved: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    post_id: 3,
    user_id: 103,
    title: "My First Smoke-Free Day: What Helped",
    content: "I decided to quit smoking on my 30th birthday. Day one was full of urges, but I used a quit tracker app and kept reminding myself this was for *me*. Keeping busy and staying hydrated helped me get through.",
    image: '../src/components/images/community-post-img-1.png',
    post_type: "STORIES",
    is_approved: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    post_id: 4,
    user_id: 104,
    title: "Common Relapse Triggers – And How to Avoid Them",
    content: "Stress, social settings, and the 'just one' mindset are common reasons people relapse. Anticipate these situations and have a plan. Remember: one cigarette is too many.",
    image: '../src/components/images/community-post-img-2.png',
    post_type: "TIPS",
    is_approved: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    post_id: 5,
    user_id: 105,
    title: "Best App I Used to Quit Smoking",
    content: "I used 'Smoke Free' – it tracked my health progress, smoke-free time, and money saved. It also sent daily motivational messages. Highly recommended!",
    image: '../src/components/images/community-post-img-1.png',
    post_type: "TIPS",
    is_approved: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    post_id: 6,
    user_id: 106,
    title: "I Failed to Quit 3 Times – Then Succeeded",
    content: "First I tried for my girlfriend, then for my health, and again when my dad was hospitalized. All failed. On my fourth attempt, I did it for myself. Now I’m free.",
    image: '../src/components/images/community-post-img-2.png',
    post_type: "STORIES",
    is_approved: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    post_id: 7,
    user_id: 107,
    title: "Deep Breathing – A Secret Weapon Against Cravings",
    content: "When I craved a cigarette, I inhaled deeply for 5 seconds, held for 5, and exhaled slowly. Repeating this 3 times really calmed me down. It works better than you'd think.",
    image: '../src/components/images/community-post-img-1.png',
    post_type: "TIPS",
    is_approved: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    post_id: 8,
    user_id: 108,
    title: "Quitting Smoking Improved My Skin",
    content: "Two months after quitting, my skin looked clearer, my lips were no longer dark, and I had fewer breakouts. It was a nice bonus I didn’t expect.",
    image: '../src/components/images/community-post-img-2.png',
    post_type: "TIPS",
    is_approved: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    post_id: 9,
    user_id: 109,
    title: "How Nicotine Replacement Helped Me Quit",
    content: "Nicotine lozenges helped me get through the first month. Though they still contain nicotine, they eased the transition. I gradually reduced the dose and stopped.",
    image: '../src/components/images/community-post-img-1.png',
    post_type: "STORIES",
    is_approved: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
  {
    post_id: 10,
    user_id: 110,
    title: "Every Smoke-Free Day Is a Win",
    content: "I put an X on my calendar for each smoke-free day. Now I have over 100 in a row. Seeing that streak grow is a great motivator to keep going.",
    image: '../src/components/images/community-post-img-2.png',
    post_type: "STORIES",
    is_approved: true,
    created_at: new Date(),
    updated_at: new Date(),
  },
];

export default CommunityPosts;