const CommunityPosts = [
  {
  post_id: 1,
  user_id: 101,
  title: "How I Quit Smoking After 15 Years",
  content: "Quitting smoking after fifteen years wasn’t something that happened overnight—it was the result of months of preparation, countless moments of doubt, and an inner voice that refused to give up. I started by writing down all the reasons I wanted to quit: my health, my family, my finances, and most importantly, my self-respect. That list became my anchor. Every single morning, I read it aloud before doing anything else. Some days I felt strong, other days I stared at those reasons with tears in my eyes, wondering if I had the strength to go one more hour without lighting up. Cravings came like waves—sudden, intense, and irrational—and when they did, I didn’t fight them head-on. I distracted myself. I drank a glass of cold water slowly, letting it fill the space a cigarette used to occupy. I’d go for a quick walk around the block or pick up the phone and talk to someone who understood what I was going through. The first three months were brutal. There were nights I couldn’t sleep, days when I snapped at loved ones for no reason, and countless moments when I nearly gave in. But each time I overcame a craving, even by the skin of my teeth, I felt stronger. Slowly, I started to notice the changes—my breathing became lighter, I wasn’t coughing in the morning anymore, and I could actually taste my food. I wasn’t constantly calculating when I’d get my next break to smoke. I began to feel more present in my life, more connected to everything around me. I stopped smelling like smoke, my clothes felt fresher, and the shame that always lingered in the back of my mind started to lift. I began saving money—at first just a little, but then I realized how much I had been spending over the years. That became another motivator: to see that cash stay in my wallet, or better yet, go toward something meaningful. Now, whenever I see someone smoking, I no longer feel envy—I feel grateful that I’m not controlled by that need anymore. It’s not easy, and it never will be, but every day I wake up and breathe without reaching for a cigarette is another day I win.",
  image: '/images/community-post-img-1.png',
  post_type: "STORIES",
  is_approved: true,
  created_at: new Date(),
  updated_at: new Date(),
  },
  {
  post_id: 2,
  user_id: 102,
  title: "5 Simple Tricks to Beat Cigarette Cravings",
  content: "Cravings hit at the worst times—after meals, during stressful work meetings, or when I was just sitting around bored—and I needed real, practical tools to keep myself from slipping. Over time, I discovered five small habits that genuinely helped me push through those urges, even when they felt overwhelming. The first and easiest one was drinking cold water. I kept a bottle with me at all times and took slow sips whenever a craving hit. The coldness gave my mouth and mind something to focus on, a quick interruption that helped me reset. Chewing sugar-free gum was another lifesaver. It gave my mouth something to do and even tricked my brain into thinking I was getting a fix. Deep breathing became my go-to in high-stress moments—I’d stop everything, inhale slowly for ten seconds, hold it, then exhale even slower. I repeated that until the tension in my chest loosened and my hands stopped shaking. Going for a walk was probably the most effective of all. Just stepping outside, feeling the air, moving my legs, and seeing people who weren’t smoking reminded me that I was changing my story. And then there were the calls. Sometimes I’d just hit dial on my sister’s number or a friend who knew what I was going through and tell them, 'I want a cigarette so bad right now.' Talking it out, even for five minutes, shifted the energy and made the craving feel like something I could outlast. These five little tools didn’t seem like much individually, but when cravings attacked, they became my personal survival kit—and I still use them today when life tries to pull me backward.",
  image: '/images/community-post-img-2.png',
  post_type: "TIPS",
  is_approved: true,
  created_at: new Date(),
  updated_at: new Date(),
  },
  {
  post_id: 3,
  user_id: 103,
  title: "My First Smoke-Free Day: What Helped",
  content: "I chose my 30th birthday as the day I would finally break free from smoking—a gift to myself after too many years of broken promises and half-hearted attempts. That first day was intense in ways I hadn’t expected. From the moment I woke up, my body screamed for nicotine, and every routine—coffee, breakfast, even brushing my teeth—felt off without a cigarette to follow. I knew I needed structure, so I downloaded a quit tracker app first thing in the morning. Watching the timer tick upward, even for just a few hours, gave me a weird sense of pride. I set reminders on my phone that said things like 'You’re doing this for YOU' and 'Stay strong, cravings pass.' And I made sure to stay busy—I rearranged my room, went for long walks, called up old friends, anything to fill the quiet that smoking used to occupy. I drank tons of water and kept a straw in my mouth most of the day just to simulate the motion of smoking, which helped more than I thought it would. I kept repeating to myself, 'Just get through today.' And somehow, I did. It wasn’t pretty—I was irritable, anxious, and had a pounding headache—but I went to bed that night without having smoked. That victory gave me a new kind of confidence I hadn’t felt in years, and even now, when hard days come, I look back at Day One and remind myself: if I did it then, I can do it now.",
  image: '/images/community-post-img-1.png',
  post_type: "STORIES",
  is_approved: true,
  created_at: new Date(),
  updated_at: new Date(),
  },
  {
  post_id: 4,
  user_id: 104,
  title: "Common Relapse Triggers – And How to Avoid Them",
  content: "I’ve come to realize that staying smoke-free isn’t just about willpower—it’s about awareness. The moments I slipped up in the past always seemed to catch me off guard, but looking back, they followed the same patterns. Stress was the biggest trigger. Whether it was a bad day at work, a fight with someone I loved, or just general overwhelm, I’d instinctively reach for a cigarette to feel like I was gaining control. Then there were the social situations—hanging out with friends who still smoked, being offered one at a party, or just stepping outside during a break and seeing others light up. That environment made it so easy to fall into the old rhythm. But the most deceptive trigger of all was the 'just one' thought. That quiet little voice in my head would say, 'Just one won't hurt. You’ve been good, you deserve this.' That mindset set me back more times than I can count. So, this time around, I made a plan. I started identifying my personal danger zones and coming up with alternatives before I got there. For stress, I journal or go for a run. For social pressure, I bring gum, have a soda in my hand, and rehearse polite ways to decline. And for that seductive voice whispering about 'just one,' I remind myself that for me, there’s no such thing—one cigarette is always the start of a spiral. Knowing my triggers has helped me stay one step ahead. It’s not about avoiding life, it’s about showing up prepared. Now, when those moments come, I face them with a mindset that’s stronger than any craving.",
  image: '/images/community-post-img-2.png',
  post_type: "TIPS",
  is_approved: true,
  created_at: new Date(),
  updated_at: new Date(),
  },
  {
  post_id: 5,
  user_id: 105,
  title: "Best App I Used to Quit Smoking",
  content: "I never thought a smartphone app could help me quit smoking, but when I downloaded 'Smoke Free,' it became more than just a tool—it became my daily accountability partner. Every time I opened it, I saw how many days I’d been smoke-free, how much money I had saved, how many cigarettes I had avoided, and even how my body was healing over time. It gave me something to look forward to. I’d wake up and check it like a scoreboard, proud of every number ticking upward. But what really kept me coming back were the motivational messages. Some days I’d be struggling—tired, triggered, thinking about giving up—and I’d get a notification that said something simple like, 'You’re stronger than this moment,' or 'Your lungs are already thanking you.' It felt like someone out there was rooting for me, even if it was just a programmed algorithm. There were times I slipped and wanted to reset the counter, but seeing all my progress made me think twice. That app held me accountable when my willpower was shaky. And the community features, like tips from other quitters and encouraging stories, reminded me that I wasn’t alone. It might sound silly to some, but 'Smoke Free' made a huge difference in my journey. Sometimes, all you need is something to reflect your progress back at you—and that little app did just that.",
  image: '/images/community-post-img-1.png',
  post_type: "TIPS",
  is_approved: true,
  created_at: new Date(),
  updated_at: new Date(),
  },
  {
  post_id: 6,
  user_id: 106,
  title: "I Failed to Quit 3 Times – Then Succeeded",
  content: "I used to think quitting smoking was just about finding the right reason or the right moment—but now I know it’s about finding the right mindset. I tried quitting three times before I finally made it. The first time was for my girlfriend. She begged me to stop, and I really wanted to prove to her that I could. But my heart wasn’t in it—I was doing it to keep her happy, not for me. The second time, I tried after a doctor warned me about early signs of lung damage. I was scared into quitting, but fear only carried me so far. I caved after a stressful week. The third time was the hardest to admit—I tried when my dad was hospitalized due to a smoking-related illness. I was overwhelmed with guilt, grief, and urgency, but even that wasn’t enough to make it stick. Every time I failed, I felt more ashamed and defeated. But the fourth time was different. I wasn’t trying to prove anything to anyone. I wasn’t reacting to fear or guilt. I just looked at myself in the mirror one morning and thought, 'I deserve better than this.' I made a commitment to *me*. I didn’t shout it to the world. I quietly built a routine, tracked my progress, forgave myself for the past, and kept moving forward. And slowly, the days added up. Now, looking back, I see those first three attempts not as failures, but as steps that brought me closer to understanding what I really needed to quit for good: self-worth. That’s what finally set me free.",
  image: '/images/community-post-img-2.png',
  post_type: "STORIES",
  is_approved: true,
  created_at: new Date(),
  updated_at: new Date(),
  },
  {
  post_id: 7,
  user_id: 107,
  title: "Deep Breathing – A Secret Weapon Against Cravings",
  content: "I used to roll my eyes when people told me to 'just breathe' through my cravings. It sounded way too simple, like a cliché ripped from a yoga poster. But one evening, caught in a full-blown craving that came out of nowhere, I decided to try it—not because I believed in it, but because I was out of options and desperate. I inhaled slowly for five seconds, held my breath for five, then exhaled slowly for another five. I repeated it three times. And to my surprise, something shifted. The tension in my chest loosened, my heartbeat slowed, and the intensity of the craving dipped just enough for me to think clearly. That one moment taught me that deep breathing wasn’t a gimmick—it was a tool. From then on, I started using it deliberately. When stress hit me at work, when I passed by someone smoking, or when I felt anxious during social gatherings, I paused and breathed with purpose. It grounded me. It reminded me that I wasn’t powerless over the urge. Over time, I didn’t just do it when I was triggered—I made it a part of my daily routine. A few minutes each morning and night, just me and my breath, letting go of the chaos and reconnecting with my goal. It became my personal ritual, my reset button. And now, whenever I feel the familiar pull of a craving, I don’t panic. I breathe. It may be simple, but it’s powerful—and it’s helped me reclaim control one breath at a time.",
  image: '/images/community-post-img-1.png',
  post_type: "TIPS",
  is_approved: true,
  created_at: new Date(),
  updated_at: new Date(),
  },
  {
  post_id: 8,
  user_id: 108,
  title: "Quitting Smoking Improved My Skin",
  content: "When I decided to quit smoking, I was mostly focused on the big stuff—my lungs, my heart, my energy levels. I never expected that one of the most visible changes would be my skin. Two months after quitting, I looked in the mirror and did a double take. The dark circles under my eyes were lighter, my complexion had a subtle glow, and the dull, ashy look I’d gotten used to was fading. My lips, once dry and discolored, were pinker and healthier-looking. Even the acne I struggled with for years started to clear up. It was like my skin was slowly waking up from a long, toxic nap. I started reading more about it and learned how smoking restricts blood flow, damages collagen, and depletes skin of oxygen—no wonder I looked older than I felt. But as the days passed without a cigarette, my body began healing from the inside out. I drank more water, exercised more, and started moisturizing daily, which I never used to bother with. Seeing those changes in the mirror gave me a new kind of motivation. I wasn’t just feeling better—I was *looking* better. It wasn’t about vanity, it was about watching the damage reverse itself and realizing my body was grateful. People began to comment, saying things like, 'You’re glowing,' or 'What’s your skincare routine?' I’d smile and say, 'I quit smoking.' It felt like a quiet victory. Every time I catch my reflection now, I see proof that the choice to quit was written all over my face.",
  image: '/images/community-post-img-2.png',
  post_type: "TIPS",
  is_approved: true,
  created_at: new Date(),
  updated_at: new Date(),
  },
  {
  post_id: 9,
  user_id: 109,
  title: "How Nicotine Replacement Helped Me Quit",
  content: "I’ll admit it—I used to judge people who used nicotine patches or lozenges to quit smoking. I thought going 'cold turkey' was the only real way. But after failing twice and suffering through unbearable withdrawal, I realized I needed help. That’s when I turned to nicotine replacement therapy, specifically lozenges. The first day I used one, I could feel my body relax within minutes. It didn’t give me a buzz—it just took the edge off. I wasn’t constantly fighting the urge or snapping at people. I could function, think clearly, and focus on building better habits without the chaos of cravings ruling my mind. Over the next few weeks, I stuck to a schedule, using fewer lozenges each week. I paired it with a quit tracker, journaling, and daily walks. I also gave myself grace—I wasn’t replacing one addiction with another; I was transitioning. And it worked. By the end of the first month, I was using half the dosage. A few weeks after that, I stopped altogether. The cravings came back a bit, but by then I had tools—deep breathing, positive affirmations, and support from friends who cheered me on. Nicotine replacement therapy didn’t make the journey effortless, but it gave me a fighting chance. I realized quitting doesn’t have to be a test of pain endurance—it can be a guided path. If you’re struggling, don’t let pride or fear stop you. There’s no shame in using a bridge to get to where you need to go.",
  image: '/images/community-post-img-1.png',
  post_type: "STORIES",
  is_approved: true,
  created_at: new Date(),
  updated_at: new Date(),
  },
  {
  post_id: 10,
  user_id: 110,
  title: "Every Smoke-Free Day Is a Win",
  content: "One of the most powerful things I did when I quit smoking was start marking an X on my calendar for each day I stayed smoke-free. It started as a simple visual habit—just something to give me a sense of momentum. But quickly, it became more than that. That red X became a symbol of victory. On tough days, when the cravings were louder than usual or when I felt emotionally drained, I’d look at that growing line of Xs and think, 'Don’t break the streak.' It was tangible proof of my strength. One day turned into five, then into two weeks, then a full month. Soon I had fifty little red marks staring back at me, reminding me that I was capable of change. When I hit 100 days, I celebrated—not with a big party, but with a quiet moment of pride. I stood in front of that calendar and smiled, thinking about how many times I wanted to give up and didn’t. That calendar taught me something valuable: success isn’t about never struggling, it’s about choosing not to give in one day at a time. Even now, I still put a mark each day, even though the cravings are rare. It’s a daily reminder that I’m winning. So if you’re just starting your journey, try it—grab a pen, mark an X, and let each day be a small, meaningful victory. They add up faster than you think.",
  image: '/images/community-post-img-2.png',
  post_type: "STORIES",
  is_approved: true,
  created_at: new Date(),
  updated_at: new Date(),
  },
];

export default CommunityPosts;